spring.application.name=${APP_NAME:shepherds_stories_backend}
spring.datasource.url=${SPRING_DATASOURCE_URL:${DATABASE_URL:}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:${DB_USER:}}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.open-in-view=false
logging.level.org.springframework.security=TRACE
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid, profile, email
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR